CREATE TABLE IF NOT EXISTS TEAMS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teamName varchar(64) NOT NULL,
    sport varchar(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS MATCHES (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matchDate varchar(64) NOT NULL,
    homeTeam varchar(64) NOT NULL,
    awayTeam varchar(64) NOT NULL,
    sport varchar(64),
    matchResult int NOT NULL
);

INSERT INTO TEAMS (teamName, sport)
SELECT * FROM (
    VALUES
        ('Blue Dragons Rowing', 'Canottaggio'),
        ('Golden Oars Club', 'Canottaggio'),
        ('Venice Rowing Team', 'Canottaggio'),
        ('Alpine Rowers', 'Canottaggio'),
        ('Tiber Watersports', 'Canottaggio'),
        ('Mediterranean Scullers', 'Canottaggio'),
        ('Northern Wave Rowing', 'Canottaggio'),
        ('Adriatic Paddlers', 'Canottaggio'),
        ('Lighthouse Rowing Club', 'Canottaggio'),
        ('Sunset Canoe & Rowing', 'Canottaggio'),


        ('Blue Dragons Rafting', 'Rafting'),
        ('Golden Paddles Club', 'Rafting'),
        ('Venice Rapids Team', 'Rafting'),
        ('Alpine Rafters', 'Rafting'),
        ('Tiber Whitewaters', 'Rafting'),
        ('Mediterranean Rafting Crew', 'Rafting'),
        ('Northern Wave Rafting', 'Rafting'),
        ('Adriatic River Rafters', 'Rafting'),
        ('Lighthouse Rafting Club', 'Rafting'),
        ('Sunset Rafting Adventures', 'Rafting'),


        ('Thunder Dragons Racing', 'Dragon Boat Racing'),
        ('Imperial Paddlers Club', 'Dragon Boat Racing'),
        ('Lunar Tide Warriors', 'Dragon Boat Racing'),
        ('Jade Serpent Crew', 'Dragon Boat Racing'),
        ('Golden Phoenix Boats', 'Dragon Boat Racing'),
        ('Stormbreaker Dragons', 'Dragon Boat Racing'),
        ('Celestial Wave Team', 'Dragon Boat Racing'),
        ('Red Fire Paddlers', 'Dragon Boat Racing'),
        ('Harmony Dragon Fleet', 'Dragon Boat Racing'),
        ('Mystic River Dragons', 'Dragon Boat Racing')
    ) AS new_teams(teamName, sport)
WHERE NOT EXISTS (SELECT 1 FROM TEAMS LIMIT 1);